---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-data-dir-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: grafana-pv
