apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
  type: ClusterIP
  selector:
    app: influxdb
