---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    db: influxdb
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/influxdb"
