{
 "title": "JVM Metrics - Jolokia 2",
 "description": "This dashboard will provide JVM metrics for a Java application instrumented with Jolokia Agent.",
 "tags": [
  "InfluxDB",
  "Telegraf",
  "Jolokia",
  "JVM"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Database", "query": "influxdb" },
   {
    "name": "podname",
    "query": "SHOW TAG VALUES FROM jolokia WITH KEY = \"host\""
   },
   {
    "name": "nodename",
    "query": "SHOW TAG VALUES FROM cpu WITH KEY =\"host\""
   },
   {
    "name": "Interval",
    "query": "10s,,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Overview - $nodename",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "nodename",
   "collapsed": true,
   "panels": [
    {
     "title": "System Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "uptime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$nodename$/" }
       ]
      }
     ]
    },
    {
     "title": "Zombies",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$Interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "select": [
        [
         { "params": [ "zombies" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$nodename$/" }
       ]
      }
     ]
    },
    {
     "title": "Load Average 5",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$Interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$nodename$/" }
       ]
      }
     ]
    },
    {
     "title": "Processes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$Interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$nodename$/" }
       ]
      }
     ]
    },
    {
     "title": "Threads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$Interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "select": [
        [
         { "params": [ "total_threads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$nodename$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$Interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_idle" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "* -1 + 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "cpu", "operator": "=", "value": "cpu-total" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$nodename$/" }
       ]
      }
     ]
    },
    {
     "title": "RAM usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$Interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$nodename$/" }
       ]
      }
     ]
    },
    {
     "title": "Swap usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$Interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$nodename$/" }
       ]
      }
     ]
    },
    {
     "title": "RootFS used",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$Interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path", "operator": "=", "value": "/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$nodename$/" }
       ]
      }
     ]
    },
    {
     "title": "IOWait",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$Interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "cpu", "operator": "=", "value": "cpu-total" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$nodename$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "ALL JVM Overview per Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "repeat": "nodename",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_hostname - Heap Memory - Committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "nodename", "operator": "=~", "value": "/^$nodename$/" }
       ]
      },
      {
       "alias": "$tag_hostname - Heap Memory - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "nodename", "operator": "=~", "value": "/^$nodename$/" }
       ]
      },
      {
       "alias": "$tag_hostname - Heap Memory - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "nodename", "operator": "=~", "value": "/^$nodename$/" }
       ]
      }
     ]
    },
    {
     "title": "GC Collection Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_hostname - GC Collection Count - $tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "hostname" ], "type": "tag" }
       ],
       "measurement": "java_garbage_collector",
       "query": "SELECT difference(\"CollectionCount\") FROM \"java_garbage_collector\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionCount" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "nodename", "operator": "=~", "value": "/^$nodename$/" }
       ]
      }
     ]
    },
    {
     "title": "GC Collection Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_hostname - GC Collection Time - $tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "hostname" ], "type": "tag" }
       ],
       "measurement": "java_garbage_collector",
       "query": "SELECT difference(\"CollectionTime\") FROM \"java_garbage_collector\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionTime" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "nodename", "operator": "=~", "value": "/^$nodename$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Stats - $podname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "podname",
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Heap Memory - Committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Heap Memory - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Heap Memory - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Non-Heap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Non-Heap Memory - Committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Non-Heap Memory - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Non-Heap Memory - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Pool - Collection Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Collection Usage - Commited",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "CollectionUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Collection Usage - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "CollectionUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Collection Usage - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "CollectionUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "GC Collection Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "GC Collection Time - $tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_garbage_collector",
       "query": "SELECT difference(\"CollectionTime\") FROM \"java_garbage_collector\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionTime" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Pool - Peak Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Peak Usage - Commited",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "PeakUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Peak Usage - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "PeakUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Peak Usage - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "PeakUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Pool - Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Usage - Commited",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "Usage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Usage - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "Usage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Usage - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Thread Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Daemon Thread Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_threading",
       "select": [
        [
         { "params": [ "DaemonThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Peak Thread Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_threading",
       "select": [
        [
         { "params": [ "PeakThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Thread Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_threading",
       "select": [
        [
         { "params": [ "ThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Class Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Loaded Class Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_class_loading",
       "select": [
        [
         { "params": [ "LoadedClassCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Unloaded Class Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_class_loading",
       "select": [
        [
         { "params": [ "UnloadedClassCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Stats - $podname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Heap Memory - Committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Heap Memory - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Heap Memory - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Non-Heap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Non-Heap Memory - Committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Non-Heap Memory - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Non-Heap Memory - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Pool - Collection Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Collection Usage - Commited",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "CollectionUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Collection Usage - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "CollectionUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Collection Usage - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "CollectionUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "GC Collection Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "GC Collection Time - $tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_garbage_collector",
       "query": "SELECT difference(\"CollectionTime\") FROM \"java_garbage_collector\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionTime" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Pool - Peak Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Peak Usage - Commited",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "PeakUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Peak Usage - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "PeakUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Peak Usage - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "PeakUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Pool - Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Usage - Commited",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "Usage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Usage - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "Usage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Usage - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Thread Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Daemon Thread Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_threading",
       "select": [
        [
         { "params": [ "DaemonThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Peak Thread Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_threading",
       "select": [
        [
         { "params": [ "PeakThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Thread Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_threading",
       "select": [
        [
         { "params": [ "ThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Class Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Loaded Class Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_class_loading",
       "select": [
        [
         { "params": [ "LoadedClassCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Unloaded Class Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_class_loading",
       "select": [
        [
         { "params": [ "UnloadedClassCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Stats - $podname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Heap Memory - Committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Heap Memory - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Heap Memory - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Non-Heap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Non-Heap Memory - Committed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Non-Heap Memory - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Non-Heap Memory - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Pool - Collection Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Collection Usage - Commited",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "CollectionUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Collection Usage - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "CollectionUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Collection Usage - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "CollectionUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "GC Collection Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "GC Collection Time - $tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_garbage_collector",
       "query": "SELECT difference(\"CollectionTime\") FROM \"java_garbage_collector\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionTime" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Pool - Peak Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Peak Usage - Commited",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "PeakUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Peak Usage - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "PeakUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Peak Usage - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "PeakUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Pool - Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Usage - Commited",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "Usage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Usage - Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "Usage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Usage - Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory_pool",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Thread Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Daemon Thread Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_threading",
       "select": [
        [
         { "params": [ "DaemonThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Peak Thread Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_threading",
       "select": [
        [
         { "params": [ "PeakThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Thread Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_threading",
       "select": [
        [
         { "params": [ "ThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Class Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Loaded Class Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_class_loading",
       "select": [
        [
         { "params": [ "LoadedClassCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "Unloaded Class Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_class_loading",
       "select": [
        [
         { "params": [ "UnloadedClassCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - Last GC Info - $podname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "podname",
   "collapsed": true,
   "panels": [
    {
     "title": "Eden Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$podname --- Eden - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Eden Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"hostname\" =~ /^$podname$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionUsage.committed" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Eden Space" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "$podname --- Eden Space - Used",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Eden Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"hostname\" =~ /^$podname$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Eden Space" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Survivor Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$podname --- Survivor Space - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Survivor Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionUsage.committed" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Survivor Space" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "$podname --- Survivor Space - Used",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Survivor Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Survivor Space" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Tenured Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$podname --- Tenured - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.CMS Old Gen.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Old Generation' OR \"name\" = 'PS MarkSweep' OR \"name\" = 'ConcurrentMarkSweep')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionUsage.committed" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Tenured Gen" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "$podname --- Tenured - Used",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.CMS Old Gen.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Old Generation' OR \"name\" = 'PS MarkSweep' OR \"name\" = 'ConcurrentMarkSweep')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionUsage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Tenured Gen" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_name --- Metaspace - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT mean(/last_gc_info_java.lang:name=$jolokia,type=GarbageCollector_LastGcInfo_memoryUsageAfterGc_Metaspace_committed/) FROM \"jolokia\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Metaspace" }
       ]
      }
     ]
    },
    {
     "title": "Compressed Class Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_name --- Compressed Class Space - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Compressed Class Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Compressed Class Space" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - Last GC Info - $podname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eden Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$podname --- Eden - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Eden Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"hostname\" =~ /^$podname$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionUsage.committed" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Eden Space" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "$podname --- Eden Space - Used",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Eden Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"hostname\" =~ /^$podname$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Eden Space" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Survivor Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$podname --- Survivor Space - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Survivor Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionUsage.committed" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Survivor Space" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "$podname --- Survivor Space - Used",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Survivor Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Survivor Space" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Tenured Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$podname --- Tenured - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.CMS Old Gen.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Old Generation' OR \"name\" = 'PS MarkSweep' OR \"name\" = 'ConcurrentMarkSweep')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionUsage.committed" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Tenured Gen" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "$podname --- Tenured - Used",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.CMS Old Gen.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Old Generation' OR \"name\" = 'PS MarkSweep' OR \"name\" = 'ConcurrentMarkSweep')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionUsage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Tenured Gen" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_name --- Metaspace - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT mean(/last_gc_info_java.lang:name=$jolokia,type=GarbageCollector_LastGcInfo_memoryUsageAfterGc_Metaspace_committed/) FROM \"jolokia\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Metaspace" }
       ]
      }
     ]
    },
    {
     "title": "Compressed Class Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_name --- Compressed Class Space - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Compressed Class Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Compressed Class Space" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - Last GC Info - $podname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eden Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$podname --- Eden - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Eden Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"hostname\" =~ /^$podname$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionUsage.committed" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Eden Space" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "$podname --- Eden Space - Used",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Eden Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Eden Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"hostname\" =~ /^$podname$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Eden Space" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Survivor Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$podname --- Survivor Space - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Survivor Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionUsage.committed" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Survivor Space" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "$podname --- Survivor Space - Used",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Survivor Space.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Par Survivor Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Survivor Space" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Tenured Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$podname --- Tenured - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.CMS Old Gen.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Old Generation' OR \"name\" = 'PS MarkSweep' OR \"name\" = 'ConcurrentMarkSweep')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionUsage.committed" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Tenured Gen" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      },
      {
       "alias": "$podname --- Tenured - Used",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.G1 Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.PS Old Gen.committed\", \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.CMS Old Gen.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Old Generation' OR \"name\" = 'PS MarkSweep' OR \"name\" = 'ConcurrentMarkSweep')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "CollectionUsage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Tenured Gen" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$podname$/" }
       ]
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_name --- Metaspace - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT mean(/last_gc_info_java.lang:name=$jolokia,type=GarbageCollector_LastGcInfo_memoryUsageAfterGc_Metaspace_committed/) FROM \"jolokia\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$podname$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Metaspace" }
       ]
      }
     ]
    },
    {
     "title": "Compressed Class Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_name --- Compressed Class Space - Commited",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_memory_pool",
       "query": "SELECT \"LastGcInfo.LastGcInfo.memoryUsageAfterGc.Compressed Class Space.committed\" FROM \"java_last_garbage_collection\" WHERE (\"EC2_IPADDRESS\" =~ /^$IP$/ AND (\"name\" = 'G1 Young Generation' OR \"name\" = 'PS Scavenge' OR \"name\" = 'ParNew')) AND $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "Usage.used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Compressed Class Space" }
       ]
      }
     ]
    }
   ]
  }
 ]
}