apiVersion: v1
kind: PersistentVolume
metadata:
  name: jmeter-data-dir-pv
spec:
  storageClassName: gp2
  claimRef:
    name: jmeter-data-dir-pv
    namespace: default
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ##VolumeId##